[package]
name = "banana-rng-firmware"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "1.0"
nb = "1.1"
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
# Panic behaviour, see https://crates.io/keywords/panic-impl for alternatives
panic-halt = "0.2.0"
cortex-m-semihosting = "0.5.0"

embedded-graphics = "0.8.1"
ssd1306 = "0.9.0"

[dependencies.stm32f1xx-hal]
version = "0.10.0"
git = "https://github.com/stm32-rs/stm32f1xx-hal.git"
rev = "6c5dc88"
features = ["stm32f103", "medium"]
